### ISSUE TITLE
moysklad-sdk

### ISSUE THREAD

**Issue by Vinni949** [holydk/moysklad-sdk#1]
Добрый день.
Подскажите пожалуйста, а позиции в заказ должны подгружаться при использовании функции 
var orders = await api.CustomerOrder.GetAllAsync();

**Comment by dkindev** [comment]
@Vinni949  Добрый день. 
Чтобы подгрузить позиции в заказы:
```csharp
var query = new ApiParameterBuilder<CustomerOrderQuery>();

query.Expand()
    .With(p => p.Positions);

var response = await api.CustomerOrder.GetAllAsync(query);
```

**Comment by Vinni949** [comment]
Но тогда появляется ошибка 
Ошибка	CS1503	Аргумент 1: не удается преобразовать из "Confiti.MoySklad.Remap.Client.ApiParameterBuilder<Confiti.MoySklad.Remap.Models.CustomerOrderQuery>" в "Confiti.MoySklad.Remap.Client.ApiParameterBuilder<Confiti.MoySklad.Remap.Models.CustomerOrdersQuery>".

**Comment by Vinni949** [comment]
Огромное спасибо.

**Comment by Vinni949** [comment]
А двойные фильтры делать можно?

**Comment by Vinni949** [comment]
Еще вопрос, есть ли фильтр товаров по атрибутам?

**Comment by dkindev** [comment]
@Vinni949 
```csharp
var query = new AssortmentApiParameterBuilder();

query.Parameter("https://online.moysklad.ru/api/remap/1.2/entity/product/metadata/attributes/83386e05-51c0-11ec-0a83-0640000001bb")
    .Should().Be("5");
```
Подходит так же в случае, когда в модели _query_ не нашлось нужного параметра. По мере нужды, добавлю все возможные параметры для фильтра.

**Comment by Vinni949** [comment]
Как можно с Вами связаться, хотел бы отблагодарить и взять еще пару подсказок ))

**Comment by dkindev** [comment]
@Vinni949 Пиши в телегу t.me/dkiselek
