### ISSUE TITLE
Отсутствует поле SalesChannel в моделях платёжных документов

### ISSUE THREAD

**Issue by Danko19** [holydk/moysklad-sdk#13]
Приветствую!

Столкнулся с тем, что в модели `PaymentOut` отсутствует поле `SalesChannel`.
Выкрутился тем, что создал в своём коде произвольную модельку и начал использовать её
![image](https://github.com/holydk/moysklad-sdk/assets/37505721/245abf69-393c-44bb-af0f-851385718cb9)

Изучил [документацию](https://dev.moysklad.ru/doc/api/remap/1.2/documents/), понял что `SalesChannel` можно добавить во все платёжные документы, т.е. в базовую модельку `PaymentDocument`
![image](https://github.com/holydk/moysklad-sdk/assets/37505721/9e513661-04be-4e45-b615-5e19929a4b56)

Пришлю PR?

**Comment by dkindev** [comment]
@Danko19 Привет! 

Да, конечно. Спасибо за поддержку!

**Comment by Danko19** [comment]
Спасибо за SDK!

PR отправил 😉

**Comment by dkindev** [comment]
@Danko19 Релизнул новую версию `0.19.0`
