### ISSUE TITLE
Работа с розничными сменами

### ISSUE THREAD

**Issue by Danko19** [holydk/moysklad-sdk#15]
Приветствую!

Появилась необходимость получить список розничных смен
https://dev.moysklad.ru/doc/api/remap/1.2/documents/#dokumenty-roznichnaq-smena

Кажется, на данный момент они не поддерживаются.
Хочу попробовать реализовать в SDK работу с ними и прислать PR

**Comment by dkindev** [comment]
@Danko19 Привет! Да, все верно. Благодарю за поддержку.

- По сути, достаточно добавить новое `RetailShiftApi`. Как пример: 

https://github.com/holydk/moysklad-sdk/blob/d091fd7eff1dc85dcb1888cf79b62c3dae99576b/src/Remap.Sdk/src/Api/SalesChannelApi.cs#L7-L8
И добавить необходимые поля в модельку `RetailShift`
https://github.com/holydk/moysklad-sdk/blob/d091fd7eff1dc85dcb1888cf79b62c3dae99576b/src/Remap.Sdk/src/Entities/Documents/RetailShift.cs#L6

- Можно пойти дальше и добавить модель для формирования Get запросов `RetailShiftQuery`. Как пример:

https://github.com/holydk/moysklad-sdk/blob/d091fd7eff1dc85dcb1888cf79b62c3dae99576b/src/Remap.Sdk/src/Models/Queries/AssortmentQuery.cs#L11
Тогда объявление `RetailShiftApi` будет выглядеть:
```csharp
public class RetailShiftApi: EntityApiAccessor<RetailShift, ApiParameterBuilder<RetailShiftQuery>, ApiParameterBuilder<RetailShiftQuery>>
{
   ...
}
```

Можешь коммитить со своего GitHub аккаунта, будешь в контрибьюторах отображаться. В прошлом релизе тебя отметил https://github.com/holydk/moysklad-sdk/releases/tag/0.19.0

**Comment by Danko19** [comment]
Привет! Подготовил PR - https://github.com/holydk/moysklad-sdk/pull/16

С ApiParameterBuilder-ом решил не заморачиваться, лично мне хватает базового для всех основных сценариев, но если что потом допилим

В саму модельку `RetailShift` добавил всё, что легко было сделать, где были примеры в других местах проекта. Для большинства сценариев этого опять же хватит, например в моём проекте нужны только сотрудник и дата

Запилил также простенький тест, по большей части чтобы руками проверить, что все поля в модельке подтягиваются. Так например нашёл баг, что в документации суммы значатся float-ом, а на деле они long-и, как и в остальных местах в МС

**Comment by dkindev** [comment]
@Danko19 Привет. Релизнул версию `0.20.0`.

С float-ми была такая же ситуация, оказывается тесты все таки нужны )
