### ISSUE TITLE
Ассортимент с expand возвращает не все поля продукта

### ISSUE THREAD

**Issue by Konstaphy** [holydk/moysklad-sdk#17]
День добрый, нужно получать SalePrice из ассортимента, апишка их возвращает (возвращает все, что есть в классе Goods), но в модельке ассортимента используется AbstractProduct, который в себе их не содержит, подскажите, пожалуйста, можно ли их получить.

**Comment by dkindev** [comment]
@Konstaphy Добрый день! Да, просто приведи `AbstractProduct` к нужному типу, его можно получить через метаданные.
https://github.com/holydk/moysklad-sdk/blob/892225aa06fbb3b1b120a752449bc47b2fbae0c4/src/Remap.Sdk/src/Client/Utils/Json/AbstractProductConverter.cs#L29-L42

**Comment by dkindev** [comment]
@Konstaphy Вообще, лучше перенести `SalePrice` в `AbstractProduct` и, возможно, другие общие свойства.

**Comment by Konstaphy** [comment]
спасибо большое!

**Comment by Konstaphy** [comment]
я могу заняться пркой с переносом общих свойств в AbstractProduct получается?

**Comment by dkindev** [comment]
@Konstaphy  Ок. Достаточно перенести одинаковые свойства

- из https://github.com/holydk/moysklad-sdk/blob/892225aa06fbb3b1b120a752449bc47b2fbae0c4/src/Remap.Sdk/src/Entities/Products/Variant.cs#L6 https://github.com/holydk/moysklad-sdk/blob/892225aa06fbb3b1b120a752449bc47b2fbae0c4/src/Remap.Sdk/src/Entities/Products/Goods.cs#L6
- в `AbstractProduct`

**Comment by Konstaphy** [comment]
создал пр, вынес все пересекающиеся свойства

**Comment by dkindev** [comment]
@Konstaphy Благодарю за поддержку. Релизнул версию `0.20.1`.
