### ISSUE TITLE
Получение списка цен для ассортимента

### ISSUE THREAD

**Issue by ermocoder** [holydk/moysklad-sdk#19]
Можно ли получить информацию о ценах через `AssortmentApi`?

[МойСклад API](https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-assortiment-poluchit-assortiment) возвращает эту информацию в поле `salePrices`.

В README есть раздел **Expand**, но я не понимаю, как это работает. Беру из `resp.Payload.Rows` экземпляр `Assortment`, но в нем нет ни поля `SalePrices`, ни какого-нибудь словаря `ExpandedData`.

Мой код сейчас:

```C#
private async Task<List<Assortment>> LoadAssortmentPage(int offset)
{
    var query = new AssortmentApiParameterBuilder();
    query.Offset(offset);
    query.Expand().With(p => p.SalePrices);
    var resp = await _api.Assortment.GetAllAsync(query);
    return resp.Payload.Rows.ToList();
}
```

PS Спасибо за библиотеку! Выглядит очень перспективно.

**Comment by dkindev** [comment]
@ermocoder Привет! Обновись до последней версии. Подробнее про `salePrices` тут #17.

Чтобы использовать `Expand`, нужно выставить `Limit = 100`.
Больше примеров в тестах:
https://github.com/holydk/moysklad-sdk/blob/c03d6e0300fe3e0ed20790ed72a495bd40263287/src/Remap.Sdk/test/Remap.Sdk.IntegrationTests/Api/AssortmentApiTests.cs#L19-L27

**Comment by ermocoder** [comment]
@holydk Спасибо за быстрый ответ! Обвновился, теперь могу получить список цен через `.Product.SalePrices`
