### ISSUE TITLE
Получение retaildemand списком

### ISSUE THREAD

**Issue by IgorCova** [holydk/moysklad-sdk#3]
В Моем складе есть ручка https://online.moysklad.ru/api/remap/1.2/entity/retaildemand?limit=5&offset=100
 В этом пакете нашел только получение retaildemand по id, а где взять все id, чтобы вызывать retaildemand по id

**Comment by dkindev** [comment]
@IgorCova Привет. Пока что реализованы не все методы, а те, которые были нужны. Добавлю полный crud для retaildemand.

**Comment by dkindev** [comment]
@IgorCova Готово. Все изменения в версии 0.16.1

**Comment by IgorCova** [comment]
Великолепно
