### ISSUE TITLE
Создание розничных продаж

### ISSUE THREAD

**Issue by Danko19** [holydk/moysklad-sdk#4]
Здравствуйте!
Мне нужна функциональность создания розничных продаж. 
В SDK нашёл только GET-метод для получения уже созданных продаж.
Могу реализовать новый метод самостоятельно и отправить PR?

**Comment by dkindev** [comment]
@Danko19 Привет. В версии 0.16.1 добавлены CRUD методы для всех API.

**Comment by Danko19** [comment]
Увидел, спасибо!
