### ISSUE TITLE
Не получается создать розничную продажу без указания смены

### ISSUE THREAD

**Issue by Danko19** [holydk/moysklad-sdk#5]
https://github.com/holydk/moysklad-sdk/blob/b11d348d25f76554a858b5128296e8e1eb5d2a5c/src/Remap.Sdk/src/Entities/Documents/RetailDemand.cs#L14

Добрый день! Для создания розничной продажи необходимо обязательно указывать смену, к которой она относится. В текущей версии библиотеки не нашёл, как это можно сделать, но кажется нашёл, что эту возможность планируется реализовать в будущем. Подскажите, входит ли данная функциональность в ближайшие планы по развитию или можно попробовать прислать свой PR? Или может быть знаете просто путь, как можно обойти это ограничение?

**Comment by dkindev** [comment]
@Danko19 Привет. Конечно, можете прислать PR. Спасибо.
