### ISSUE TITLE
Есть большая необходимость через апишку получать отчеты

### ISSUE THREAD

**Issue by IgorCova** [holydk/moysklad-sdk#7]
Конкретно нужен [Отчет Прибыльность](https://dev.moysklad.ru/doc/api/remap/1.2/reports/#otchety-otchet-pribyl-nost) еще конкретнее [Получить Прибыльность по товарам](https://dev.moysklad.ru/doc/api/remap/1.2/reports/#otchety-otchet-pribyl-nost-poluchit-pribyl-nost-po-towaram)

Если возможность расширить sdk?

**Comment by IgorCova** [comment]
В целом могу сам попробовать добавить и скинуть ПР

**Comment by dkindev** [comment]
@IgorCova Привет. Конечно, присылай PR. Пример похожего API можешь посмотреть в [AssortmentApi](https://github.com/holydk/moysklad-sdk/blob/dev/src/Remap.Sdk/src/Api/AssortmentApi.cs).

**Comment by IgorCova** [comment]
https://github.com/holydk/moysklad-sdk/pull/8
